import { createHash, randomBytes, randomUUID } from 'node:crypto';
const b64url = (value) => Buffer.from(value).toString('base64url');
const configured = (c) => [c.tokenUrl, c.apiBaseUrl, c.clientId, c.clientSecret, c.redirectUri, c.paths.search, c.paths.product, c.paths.topUp, c.paths.purchase].every(Boolean);
const path = (template, values = {}) => Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, encodeURIComponent(value)), template);
/** Endpoint paths are supplied by the registered CatBuy integration; none are guessed by MogBuy. */
export class CatBuyClient {
  constructor(config, tokenStore, fetchImpl = fetch) { Object.assign(this, { config, tokenStore, fetch: fetchImpl, pending: new Map() }); }
  authorizationUrl(userId) { if (!this.config.authorizeUrl || !configured(this.config)) throw new Error('CatBuy authorized OAuth integration is not fully configured'); const state = randomUUID(); const verifier = b64url(randomBytes(32)); this.pending.set(state, { userId, verifier, expiresAt: Date.now() + 600_000 }); const url = new URL(this.config.authorizeUrl); url.search = new URLSearchParams({ response_type: 'code', client_id: this.config.clientId, redirect_uri: this.config.redirectUri, scope: this.config.scopes, state, code_challenge: createHash('sha256').update(verifier).digest('base64url'), code_challenge_method: 'S256' }); return url; }
  async completeAuthorization({ state, code }) { const pending = this.pending.get(state); this.pending.delete(state); if (!pending || pending.expiresAt < Date.now() || !code) throw new Error('Invalid or expired OAuth callback'); const response = await this.fetch(this.config.tokenUrl, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', code, redirect_uri: this.config.redirectUri, client_id: this.config.clientId, client_secret: this.config.clientSecret, code_verifier: pending.verifier }) }); if (!response.ok) throw new Error('CatBuy token exchange failed'); await this.tokenStore.save(pending.userId, await response.json()); }
  async request(userId, requestPath, options = {}) { if (!configured(this.config)) throw new Error('CatBuy authorized API integration is not fully configured'); const token = await this.tokenStore.get(userId); if (!token?.access_token) throw new Error('No CatBuy account linked'); const response = await this.fetch(new URL(requestPath, this.config.apiBaseUrl), { ...options, headers: { authorization: `Bearer ${token.access_token}`, accept: 'application/json', ...options.headers } }); if (!response.ok) throw new Error(`CatBuy request failed (${response.status})`); return response.json(); }
  search(userId, query) { return this.request(userId, `${this.config.paths.search}${this.config.paths.search.includes('?') ? '&' : '?'}q=${encodeURIComponent(query)}`); }
  product(userId, id) { return this.request(userId, path(this.config.paths.product, { id })); }
  topUpBalance({ userId, amountCents, idempotencyKey }) { return this.request(userId, this.config.paths.topUp, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': idempotencyKey }, body: JSON.stringify({ amount_cents: amountCents }) }); }
  purchase({ userId, productId, amountCents, idempotencyKey }) { return this.request(userId, this.config.paths.purchase, { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': idempotencyKey }, body: JSON.stringify({ product_id: productId, amount_cents: amountCents }) }); }
}
