// The app session is an HttpOnly cookie. CatBuy credentials, passwords, and tokens never enter this page.
let selected;
const money = (cents) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
const api = async (url, opts = {}) => { const response = await fetch(url, opts); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Request failed'); return data; };
const status = (id, message) => { document.querySelector(id).textContent = message; };
const connect = () => location.assign('/api/catbuy/connect');
document.querySelector('#connect').onclick = connect; document.querySelector('#hero-connect').onclick = connect;
document.querySelector('#search').onclick = async () => { const query = document.querySelector('#query').value.trim(); if (!query) return status('#search-status', 'Enter an item to search.'); status('#search-status', 'Searching CatBuy…'); try { const items = await api(`/api/products?q=${encodeURIComponent(query)}`); const results = document.querySelector('#results'); results.replaceChildren(...items.map(item => { const button = document.createElement('button'); button.className = 'product'; button.innerHTML = `<strong>${item.name}</strong><small>From ${money(item.pricing.itemCents)}</small>`; button.onclick = () => showCheckout(item); return button; })); status('#search-status', items.length ? `${items.length} item${items.length === 1 ? '' : 's'} found.` : 'No items found.'); } catch (error) { status('#search-status', `Search unavailable: ${error.message}`); } };
async function showCheckout(product) { try { selected = product; status('#status', ''); const q = await api('/api/quote', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ productId: product.id }) }); document.querySelector('#checkout').hidden = false; document.querySelector('#price').innerHTML = [['Source item price',q.itemCents],['Shipping / source fees',q.shippingCents + q.providerFeeCents],['MogBuy service fee',q.serviceFeeCents],['Total charged',q.totalChargedCents]].map(([label,value]) => `<dt>${label}</dt><dd>${money(value)}</dd>`).join(''); document.querySelector('#checkout').scrollIntoView({ behavior: 'smooth', block: 'nearest' }); } catch (error) { status('#search-status', `Could not prepare checkout: ${error.message}`); } }
document.querySelector('#buy').onclick = async () => { if (!selected) return; const key = crypto.randomUUID(); status('#status', 'Confirming balance top-up and placing your order…'); try { const order = await api('/api/checkout', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': key }, body: JSON.stringify({ productId: selected.id }) }); status('#status', order.status === 'completed' ? 'Order confirmed — your CatBuy purchase has been placed.' : `Order status: ${order.status}. ${order.failureReason ?? ''}`); } catch (error) { status('#status', `Checkout failed: ${error.message}`); } };
